import Inquiry from './Inquiry';
import Link from 'next/link';
import {categories,products,imageUrl,Product,siteUrl} from '../data';
import {JsonLd} from '../seo';
export function responsiveImageSet(path:string){
 if(!path.endsWith('.webp')||(!path.startsWith('/assets/honey-gallery/')&&!path.startsWith('/assets/blog/')))return undefined;
 const stem=path.slice(0,-5);
 return `${stem}-480.webp 480w, ${stem}-768.webp 768w, ${path} 1536w`;
}
export function Photo({name,alt,priority=false,className=''}:{name:string;alt:string;priority?:boolean;className?:string}){const src=imageUrl(name);return <img className={className} src={src} srcSet={name.startsWith('/')?responsiveImageSet(src):(name==='honey-bottle-360ml'?[480,850,1440]:[480,960,1440]).map(w=>`${imageUrl(name,w)} ${w}w`).join(', ')} sizes="(max-width: 700px) 92vw, (max-width: 1000px) 46vw, 600px" alt={alt} width={name.startsWith('/')?1536:960} height={name.startsWith('/')?1024:960} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':'auto'}/>;}
export function Breadcrumbs({items}:{items:{name:string;url:string}[]}){const all=[{name:'Home',url:'/'},...items];return <><nav className="breadcrumbs" aria-label="Breadcrumb">{all.map((x,i)=><span key={x.url}>{i>0&&' / '}<Link href={x.url} aria-current={i===all.length-1?'page':undefined}>{x.name}</Link></span>)}</nav><JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:all.map((x,i)=>({'@type':'ListItem',position:i+1,name:x.name,item:siteUrl+x.url}))}}/></>;}
export function ProductCard({p}:{p:Product}){const src=`/assets/honey-gallery/${p.slug}/full.webp`;return <article className="product-card"><Link href={`/products/${p.slug}/`} className="product-image"><img src={src} srcSet={responsiveImageSet(src)} sizes="(max-width: 700px) 46vw, (max-width: 1000px) 46vw, 400px" alt={p.title} width={1536} height={1024} loading="lazy" decoding="async"/></Link><div className="product-card-copy"><p className="meta">{p.material} · {p.variants.length>3?`${Math.min(...p.variants.map(v=>parseFloat(v.volume)))}–${Math.max(...p.variants.map(v=>parseFloat(v.volume)))} ml`:p.volume}</p><h3><Link href={`/products/${p.slug}/`}>{p.title}</Link></h3><p>{p.description.split('. ')[0].replace(/\.$/,'')}.</p><p className="note">{p.variants.length} {p.variants.length===1?'option':'options'}</p><Link className="text-link" href={`/products/${p.slug}/`}>View specifications <span aria-hidden="true">↗</span></Link></div></article>;}
export function ProductGrid({items=products}:{items?:Product[]}){return <div className="product-grid">{items.map(p=><ProductCard p={p} key={p.slug}/>)}</div>;}
export function CTA({title}:{title?:string}={}){return <section className="cta"><div className="wrap split"><div><h2>{title||"Request a Honey Packaging Quote"}</h2><p>Send your preferred container, target honey weight, order quantity and destination. Gracepack will confirm product options, sample availability and quotation details.</p></div><Inquiry id="footer-inquiry" source="Bottom inquiry form" lazy/></div></section>;}
export function CategoryLinks(){return <div className="category-links">{categories.map(c=><Link key={c.id} href={`/${c.slug}/`}>{c.title} <span aria-hidden="true">↗</span></Link>)}</div>;}
export function FAQ({items}:{items:[string,string][]}){return <div className="faq-list">{items.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>;}
export function Intro({title,description,image}:{title:string;description:string;image?:string}){return <section className={`intro ${image?'with-image':''}`}><div className="wrap split"><div><h1>{title}</h1><p className="lead">{description}</p></div>{image&&<Photo name={image} alt={title} priority/>}</div></section>;}
