import Link from 'next/link';
import {Product} from '../data';
import specifications from '../../content/honey-specifications.json';
import copyData from '../../content/honey-product-copy.json';
import {ModelDetailsLink} from './ModelDetailsLink';
export const productCopy:Record<string,(typeof copyData)[keyof typeof copyData]>=copyData;

type Spec=(typeof specifications)[keyof typeof specifications];
const specs:Record<string,Spec>=specifications;
const closureDesign:Record<string,string>={
 'flip-top-honey-bottle-caps':'A one-piece PP construction combines a ribbed screw skirt, centered dispensing outlet and attached hinged lid for repeated opening and reclosure.',
 'pointed-nozzle-honey-caps':'The screw-on base supports a tapered nozzle that directs honey through a narrow outlet, with a closing tip that protects the opening between uses.',
 'inverted-honey-bottle-valve-caps':'A wide supporting base keeps the bottle stable in a cap-down position. The closure can incorporate a silicone valve for controlled flow and cleaner reclosure.',
 'plastic-screw-caps-for-honey-jars':'The ribbed PP skirt provides grip for opening and reclosure. The threaded design can be paired with a liner or seal for the specified PET jar finish.',
 'metal-twist-off-honey-jar-lids':'A formed tinplate shell, lug pattern and food-contact sealing compound create the closing system for compatible glass jar finishes.',
 'aluminum-screw-caps-for-honey-jars':'The lightweight aluminum shell provides a metallic surface finish over a threaded closure format, with liner options for compatible PET jars.'
};
function Rows({items}:{items:[string,string][]}){return <table className="identity-table"><tbody>{items.filter(([,value])=>value).map(([label,value])=><tr key={label}><th scope="row">{label}</th><td>{value}</td></tr>)}</tbody></table>}
function variantLabel(p:Product,v:Product['variants'][number]){const same=p.variants.filter(x=>x.volume===v.volume);return `${v.volume}${same.length>1?' · Option '+(same.indexOf(v)+1):''}`}
function known(value:string){return !/confirm|request|see model/i.test(value)?value:''}
function ClosureSpecificationContent({product:p,variant:v}:{product:Product;variant:Product['variants'][number]}){
 const s=specs[v.specId];
 return <div className="identity-content"><div className="identity-top"><div><p className="section-label">CLOSURE & COMPATIBILITY</p><h3>{p.title}</h3><Rows items={[
  ['Closure material',p.material],['Compatible container / finish',v.volume],['Closure type',v.closure],['Outlet, liner or valve',v.honeyWeight],['Closure weight',s.capWeight]
 ]}/></div></div><div className="identity-columns"><div><h4>Closure construction</h4><p>{closureDesign[p.slug]}</p></div><div><h4>Available configurations</h4><p>Color, finish, outlet, liner or valve and packing options are prepared for the selected container and order quantity.</p></div></div><p className="identity-confirm"><strong>Gracepack matching support: </strong>share the bottle or jar model, neck drawing or physical sample. We will review the compatible finish, sealing components and assembled performance for the proposed pack.</p><div className="identity-footer"><span>Closure samples can be supplied with a compatible container</span><Link className="button" href={`/contact/?product=${encodeURIComponent(p.title)}&request=sample`}>Request product samples ↗</Link></div></div>
}
function SpecificationContent({product:p,variant:v}:{product:Product;variant:Product['variants'][number]}){
 const s=specs[v.specId];
 const label=variantLabel(p,v);
 const missing=[!s.bodyWeight&&'body weight',!s.capWeight&&'cap weight',!s.overallHeight&&'assembled height',!s.bodyHeight&&'body height',!known(v.neck)&&'full neck finish',!s.moq&&'MOQ',!s.cartonCount&&'carton quantity',!s.cartonDimensions&&'carton size',!known(v.honeyWeight)&&'honey fill'].filter(Boolean);
 const dimensions:[string,string][]=[['Overall height (with cap)',s.overallHeight],['Body height (without cap)',s.bodyHeight],['Body diameter (D)',s.diameter],['Body width (W)',s.width],['Body depth (F)',s.depth],['Mouth C (reference)',s.mouthReference]];
 const packing:[string,string][]=[['Minimum order quantity',s.moq],['Units per carton',s.cartonCount],['Outer carton dimensions',s.cartonDimensions],['Carton net weight',s.netWeight],['Carton gross weight',s.grossWeight]];
 return <div className="identity-content"><div className="identity-top"><div><p className="section-label">CONTAINER & CLOSURE</p><h3>{variantLabel(p,v)}</h3><Rows items={[
 ['Container material',p.material],['Water capacity',known(v.volume)],['Reference honey fill',known(v.honeyWeight)],['Body weight',s.bodyWeight],['Closure material',known(v.closure)],['Cap weight',s.capWeight],['Neck finish',known(v.neck)]
 ]}/></div></div><div className="identity-columns"><div><h4>Dimensions & fit</h4><Rows items={dimensions}/>{!dimensions.some(([,v])=>v)&&<p className="note">A dimensioned drawing is available for {label}.</p>}</div><div><h4>Order & shipping data</h4><Rows items={packing}/>{!packing.some(([,v])=>v)&&<p className="note">Current minimum order and packing data for {label} are supplied with the quotation.</p>}</div></div>{(missing.length>0||s.issues.length>0)&&<p className="identity-confirm"><strong>Gracepack will verify for {variantLabel(p,v)}: </strong>{missing.length>0?missing.join(', ')+'. ':''}{s.issues.length>0?'Remaining dimensions and shipping details are completed with the quotation.':''}</p>}<div className="identity-footer"><span>The selected size and closure are verified for the order</span><Link className="button" href={`/contact/?product=${encodeURIComponent(p.title+' — '+label)}&request=sample`}>Request {variantLabel(p,v)} sample ↗</Link></div></div>
}
export function ProductSpecifications({product:p}:{product:Product}){
 const isClosure=p.categories.includes('closures');
 if(isClosure)return <section className="section soft" id="specifications"><div className="wrap"><div className="section-heading"><div><p className="section-label">PRODUCT DETAILS</p><h2>Closure Features & Specifications</h2></div><p>Review the construction, dispensing or sealing design, compatible packaging and available order options.</p></div><div className="identity-list">{p.variants.map(v=><article className="identity-card single-specification" key={v.specId}><ClosureSpecificationContent product={p} variant={v}/></article>)}</div><div className="spec-reading-note"><h3>Container Matching & Sample Testing</h3><p>Gracepack reviews the complete thread or lug pattern, sealing surface, outlet, liner or valve and cap application requirements against the selected bottle or jar.</p><p>The quotation records the agreed material, color, dimensions, tolerances, component assembly, minimum order and carton configuration.</p></div></div></section>;
 const single=p.variants.length===1;
 return <section className="section soft" id="specifications"><div className="wrap"><div className="section-heading"><div><p className="section-label">TECHNICAL DETAILS</p><h2>{single?'Product Specifications':'Sizes & Product Specifications'}</h2></div><p>{single?`Dimensions, closure and packing references for ${p.title}.`:'The size overview brings capacities, closures and available specifications together.'}</p></div>{!single&&<div className="model-comparison" role="region" aria-label="Model comparison" tabIndex={0}><table><caption>{p.title} — size overview</caption><thead><tr><th scope="col">Size option</th><th scope="col">Water capacity</th><th scope="col">Reference honey fill</th><th scope="col">Closure</th><th scope="col">Specifications</th></tr></thead><tbody>{p.variants.map(v=><tr key={v.specId}><th scope="row">{variantLabel(p,v)}</th><td>{known(v.volume)||'On request'}</td><td>{known(v.honeyWeight)||'On request'}</td><td>{known(v.closure)||'On request'}</td><td><ModelDetailsLink id={`option-${p.variants.indexOf(v)+1}`} model={variantLabel(p,v)}/></td></tr>)}</tbody></table></div>}<div className="identity-list">{p.variants.map(v=>single?<article className="identity-card single-specification" key={v.specId} id={`model-option-${p.variants.indexOf(v)+1}`}><SpecificationContent product={p} variant={v}/></article>:<details className="identity-card" key={v.specId} id={`model-option-${p.variants.indexOf(v)+1}`}><summary><span className="identity-model">{variantLabel(p,v)}</span><span>Dimensions, closure & packing</span><span className="identity-toggle" aria-hidden="true">+</span></summary><SpecificationContent product={p} variant={v}/></details>)}</div><div className="spec-reading-note"><h3>Capacity, Closure & Order Specification</h3><p>The listed volume is water capacity. Gracepack verifies the working fill level and headspace with the proposed honey fill, then matches the full neck finish, cap and seal through the dimensioned drawing and assembled sample.</p><p>The quotation records tolerances, body and cap colors, the matched cap and liner, seal dimensions, stock status and final packing configuration. MOQ and carton data reflect the selected assembly and decoration.</p></div></div></section>
}
export function ProductOrderDetails({product:p}:{product:Product}){
 const copy=productCopy[p.slug];
 const isClosure=p.categories.includes('closures');
 if(isClosure)return <><section className="section" id="application"><div className="wrap"><div className="section-heading"><div><p className="section-label">APPLICATION & FIT</p><h2>{copy.headline}</h2></div><p>Review the closure with the selected bottle or jar and your filling process.</p></div><div className="spec-support-grid"><article><span>01</span><h3>Closure application</h3><p>{copy.application}</p></article><article><span>02</span><h3>Filling, sealing & use</h3><p>Confirm cap application, sealing performance, opening and reclosure under the intended filling and handling conditions. Test dispensing closures with your honey at the intended serving temperature.</p></article><article><span>03</span><h3>Color & presentation</h3><p>{copy.artwork}</p></article></div></div></section><section className="section soft" id="ordering"><div className="wrap"><div className="section-heading"><div><p className="section-label">CUSTOMIZATION & COMMERCIAL DETAILS</p><h2>Closure Options & Ordering</h2></div><Link className="text-link" href="/custom-honey-packaging/">Explore custom packaging ↗</Link></div><div className="identity-columns order-columns"><div><h3>Options to Confirm</h3><Rows items={[
 ['Color and finish','Available colors and metal finishes depend on the selected closure, quantity and approved physical sample.'],['Outlet, liner or valve','List every required component in the quotation and approve the assembled sample.'],['Packing',copy.packing]
 ]}/></div><div><h3>Samples, Lead Times & Pricing</h3><Rows items={[
 ['Samples','Request the closure together with its compatible bottle or jar. Sample availability and courier cost are confirmed before dispatch.'],['Production planning','Timing depends on material, color, component assembly, quantity and approval status.'],['Price breakdown','Request closure, liner or valve, color, assembly and packing costs for the chosen configuration.'],['Quotation terms','Specify quantity, destination and preferred shipping terms. Currency, freight, payment terms and validity are stated in the quote.']
 ]}/></div></div></div></section><section className="section" id="product-quality"><div className="wrap split"><div><p className="section-label">QUALITY & DOCUMENTATION</p><h2>Closure Material & Performance Checks</h2><p>Request the available material documentation for the selected cap, lid, liner or valve. Confirm that each document applies to the quoted component and intended conditions of use.</p><Link className="text-link" href="/quality/">View certificates & test reports ↗</Link></div><div className="product-quality-box"><h3>Agree the inspection plan</h3><ul><li>Appearance, color, dimensions and agreed tolerances.</li><li>Fit and application on the selected bottle or jar.</li><li>Outlet, liner, valve and sealing performance where specified.</li><li>Opening, dispensing, reclosure and filled-pack leakage checks.</li><li>Packing quantity and protection during shipment.</li></ul><p className="note">Agree the required checks and acceptance criteria before ordering.</p></div></div></section></>;
 const glass=p.material==='Glass', jar=p.categories.includes('plastic-jars')||glass, inverted=p.slug.includes('inverted'),bear=p.categories.includes('bear'),handled=p.slug.includes('handles');
 const trial=inverted?'Check cap-down standing stability, outlet flow, valve operation if specified, resealing and leakage with the actual honey.':handled?'Check the handle attachment and lifting performance at your target filled weight, together with cap fit and carton clearance.':glass?'Check the glass rim, matching lid, sealing surface and filled-pack protection. Approve dividers and the complete gift or shipping pack.':jar?'Check spoon access, filling nozzle clearance, cap application and the selected liner or seal with your honey.':bear?'Check the front label panel, grip, dispensing opening and cap fit on this bear shape. Evaluate flow with your actual honey.':'Check the dispensing outlet, grip, cap operation and label panel on the selected model. Evaluate flow and resealing with your actual honey.';
 return <><section className="section" id="application"><div className="wrap"><div className="section-heading"><div><p className="section-label">APPLICATIONS & FILLING</p><h2>{copy.headline}</h2></div><p>Packaging performance, filling considerations and presentation details for this product.</p></div><div className="spec-support-grid"><article><span>01</span><h3>Product applications</h3><p>{copy.application}</p></article><article><span>02</span><h3>Filling & storage</h3><p>{glass?'Filling temperature, heating and cooling rates are evaluated with the selected jar and lid. The complete assembly, rather than the glass body alone, determines suitability for a thermal process.':'Gracepack reviews the filling temperature, holding time and cooling method against the bottle and closure limits. The assembled pack is then validated under the intended filling conditions.'}</p><p>Approved storage conditions and stacking limits depend on the selected bottle, closure and filling process and are recorded with the product specification.</p></article><article><span>03</span><h3>Label & presentation</h3><p>{copy.artwork}</p></article></div></div></section><section className="section soft" id="ordering"><div className="wrap"><div className="section-heading"><div><p className="section-label">CUSTOMIZATION & COMMERCIAL DETAILS</p><h2>Customization & Ordering</h2></div><Link className="text-link" href="/custom-honey-packaging/">Explore custom packaging ↗</Link></div><div className="identity-columns order-columns"><div><h3>Decoration & Design Options</h3><Rows items={[
 ['Printing / special finishes','Silk-screen printing, transfer decoration or special finishes are assessed for the selected surface and artwork.'],['New shape or embossing','Requires a design and tooling feasibility review; tooling rights and costs are confirmed in writing.'],['Packaging design',copy.packing]
 ]}/></div><div><h3>Samples, Lead Times & Pricing</h3><Rows items={[
 ['Samples','Request samples for your selected product and size. Availability, any sample charge and courier cost are confirmed before dispatch.'],['Production planning','General production planning reference: 15–20 days. Your model, quantity, decoration and approvals determine the confirmed schedule.'],['Custom development','General custom-project planning reference: 4–6 weeks; new tooling and sampling are scheduled separately.'],['Price breakdown','Request body, cap, liner/seal, decoration, tooling and packing costs for the chosen assembly.'],['Quotation terms','Specify quantity, destination and preferred shipping terms. Currency, tax, freight, payment terms and validity are stated in the quote.']
 ]}/><p className="note">Planning references are not a delivery commitment or a statement of stock availability.</p></div></div></div></section><section className="section" id="product-quality"><div className="wrap split"><div><p className="section-label">QUALITY & DOCUMENTATION</p><h2>Material Reports & Quality Checks</h2><p>{glass?'Request glass-body and lid documentation for the selected supplier and assembly. Plastic test reports and the plastic manufacturing scope of ISO 22000 do not certify this glass jar.':'PET sample reports are available for review, including extractives, BPA and the specified PPWR substance tests. Confirm applicability to your selected body, resin and closure before ordering.'}</p><Link className="text-link" href="/quality/">View certificates & test reports ↗</Link></div><div className="product-quality-box"><h3>Agree the inspection plan</h3><ul><li>Appearance, dimensions, body weight and agreed tolerances.</li><li>{glass?'Rim condition, lid engagement and the selected seal.':'Bottle-to-cap fit, cap application and seal integrity.'}</li><li>{trial}</li><li>Filled-pack leakage and transport tests using the agreed procedure.</li><li>Applicable food-contact documentation for the body, closure and liner.</li></ul><p className="note">Agree the required tests and acceptance criteria before ordering. Available reports apply to the samples and test conditions identified in each document.</p></div></div></section></>
}
