import PPWRReports from './PPWRReports';
import Link from 'next/link';
import {Photo} from './Common';

export function ProofStrip(){return <div className="proof-strip"><div className="wrap"><Link href="/factory/"><strong>Cixi, Ningbo</strong><span>Plastic packaging experience since 1999</span></Link><Link href="/quality/"><strong>ISO 22000:2018</strong><span>Plastic bottle & cap processing scope</span></Link><Link href="/quality/"><strong>SGS test documents</strong><span>Review the sample and material covered</span></Link><Link href="/contact/?request=sample"><strong>Samples before approval</strong><span>Check the complete bottle-and-cap pack</span></Link></div></div>;}

const uses=[
{image:'/assets/honey-gallery/pet-honey-bear-bottle-320ml/application.webp',title:'Branded honey lines',text:'A familiar bear shape with space for your brand. Compare target fill weight, pack height and cap opening.',href:'/honey-bear-bottles/',link:'Explore bear bottles'},
{image:'/assets/honey-gallery/ribbed-honey-squeeze-bottle-180ml/application.webp',title:'Squeeze dispensing',text:'For honey served directly from the bottle. Review grip, squeeze response and dispensing performance with your honey.',href:'/honey-squeeze-bottles/',link:'Compare squeeze formats'},
{image:'/assets/honey-gallery/hexagon-glass-honey-jars/application.webp',title:'Glass honey collections',text:'Build a coordinated range around glass shape and lid finish. Check label fit and protective packing across the selected sizes.',href:'/glass-honey-jars/',link:'Browse glass jars'},
{image:'/assets/honey-gallery/mini-glass-honey-jar-25ml/application.webp',title:'Tasting sets & gift packs',text:'Compact jars for honey samples, event favors and gift boxes. Plan the lid, small label and box insert together.',href:'/mini-honey-jars/',link:'Find mini jars'}];
export function HoneyApplications({title}:{title?:string}={}){return <section className="section honey-applications"><div className="wrap"><div className="section-heading"><div><p className="section-label">PRODUCT LINES, DISPENSING & GIFT PACKAGING</p><h2>{title||<>Honey Packaging Applications</>}</h2></div><p>Choose the container and closure around how your honey will be served, stored and presented.</p></div><div className="use-grid">{uses.map(x=><article key={x.title}><Link href={x.href}><Photo name={x.image} alt={x.title+' packaging options'}/></Link><div><h3>{x.title}</h3><p>{x.text}</p><Link className="text-link" href={x.href}>{x.link} ↗</Link></div></article>)}</div></div></section>;}

export function DocumentProof({title,includePPWR=true}:{title?:string;includePPWR?:boolean}={}){return <section className="section soft"><div className="wrap"><div className="section-heading"><div><p className="section-label">SUPPLIER QUALIFICATION</p><h2>{title||<>Gracepack Certifications & Test Reports</>}</h2></div><p>Download the manufacturing certificate and sample-specific material reports. Contact our team to confirm which documents apply to your selected container and closure.</p></div><div className="trust-doc-grid"><article className="trust-certificate"><a href="/documents/iso-22000-certificate.pdf" target="_blank" rel="noopener"><img src="/assets/honey/iso-22000-2026.webp" alt="ISO 22000:2018 certificate 051FSMS2200014" width="707" height="1000" loading="lazy"/></a><div><span className="section-label">MANAGEMENT SYSTEM</span><h3>ISO 22000:2018</h3><p>Cixi Yangen Plastic Industry Co., Ltd. Plastic bottle and cap processing. Certificate expiry: January 20, 2028.</p><a className="text-link" href="/documents/iso-22000-certificate.pdf" target="_blank" rel="noopener">Open original certificate ↗</a></div></article><div className="trust-reports"><article><p className="section-label">PET · SGS · MARCH 2026</p><h3>PET bottle extractives report</h3><p>Report NGBEC26002025404 identifies a transparent PET bottle sample. The report references US FDA 21 CFR 177.1630; it is a sample test, not FDA approval of the range.</p><a className="text-link" href="/documents/pet-extractives-test-2026.pdf" target="_blank" rel="noopener">Read the test report ↗</a></article><article><p className="section-label">MATERIAL-SPECIFIC DOCUMENTS</p><h3>BPA and LDPE reports</h3><p>Separate reports are available for PET BPA testing and LDPE migration testing. Match the report to the proposed material and component.</p><Link className="text-link" href="/quality/">View the document library ↗</Link></article></div></div>{includePPWR&&<PPWRReports embedded/>}</div></section>;}

const stages=[['Define the honey pack','Share target honey weight, filling conditions, quantity, destination and dispensing preference.','A clear packaging brief'],['Compare the components','Select the bottle or jar, then review the neck finish, cap, liner and label area together.','Selected bottle or jar and matched closure'],['Evaluate the sample','Check actual fill level, cap fit, dispensing, reclosure and handling with your honey.','Your sample feedback'],['Confirm the specification','Approve artwork, colors, any tooling, included components and order-specific requirements.','Approved sample, artwork and specifications'],['Agree inspection & packing','Set the checks to be performed, carton count, protection and any pallet or shipment-photo needs.','An inspection and packing brief'],['Prepare delivery & reorders','Confirm shipping arrangements and keep model, artwork and closure references for the next order.','Shipping instructions and reorder specifications']];
export function OrderJourney({title}:{title?:string}={}){return <section className="section"><div className="wrap"><div className="section-heading"><div><p className="section-label">FROM FIRST BRIEF TO REPEAT ORDER</p><h2>{title||<>How to Order from Gracepack</>}</h2></div><p>From your initial requirements to repeat orders, agree the container, samples, production specifications and shipment details with Gracepack. Lead times are confirmed in your quotation.</p></div><ol className="journey-grid">{stages.map(([title,text,output],i)=><li key={title}><span className="journey-number">0{i+1}</span><h3>{title}</h3><p>{text}</p><div className="journey-output">{output}</div></li>)}</ol><Link className="text-link" href="/contact/">Start with your packaging brief ↗</Link></div></section>;}

export function FactoryEvidence({title}:{title?:string}={}){return <section className="section factory-evidence"><div className="wrap"><div className="section-heading"><div><p className="section-label">MANUFACTURING & SOURCING</p><h2>{title||<>Gracepack Manufacturing & Development</>}</h2></div><p>Compare physical samples and review bottle drawings with our team. We support plastic bottle development and coordinate glass jars, closures and packing through our supply partners.</p></div><div className="factory-proof-grid"><figure><Photo name="showroom" alt="Gracepack sample shelves displaying honey bear bottles and other packaging"/><figcaption><strong>Bottle & jar samples</strong><span>Compare the bottle shape, cap and label area in an assembled pack.</span></figcaption></figure><figure><Photo name="engineering" alt="Bottle drawing and component review at Gracepack"/><figcaption><strong>Drawings and component review</strong><span>Discuss dimensions and closure fit before approving a custom plastic bottle.</span></figcaption></figure></div><div className="capability-points"><div><h3>Plastic bottle manufacturing</h3><p>Choose from existing PET honey bottles or submit a drawing for custom plastic bottle development.</p></div><div><h3>Glass jar sourcing</h3><p>Select glass jars and matching metal lids from our sourced range, with specifications and documentation reviewed for your order.</p></div><div><h3>Container & closure coordination</h3><p>Coordinate the bottle or jar, matched closure, artwork and outer packing before approving production.</p></div></div><Link className="text-link" href="/factory/">Explore factory and development support ↗</Link></div></section>;}

export function CustomRoutes(){return <section className="section soft"><div className="wrap"><p className="section-label">THREE WAYS TO START</p><h2>Honey Packaging Customization Options</h2><div className="custom-route-grid"><article><span>01 / EXISTING FORMAT</span><h3>Select a catalog pack</h3><p>Start with an existing container and matching closure. Check samples against your filling and packing process.</p><Link href="/products/" className="text-link">Browse the range ↗</Link></article><article><span>02 / BRAND PRESENTATION</span><h3>Customize labels & colors</h3><p>Review label placement, available cap colors and outer packaging around the selected bottle or jar.</p><Link href="/contact/" className="text-link">Discuss your artwork ↗</Link></article><article><span>03 / CUSTOM PLASTIC SHAPE</span><h3>Develop a bottle</h3><p>Share a reference or drawing. Tooling, sampling, costs and feasibility are assessed for the individual project.</p><Link href="/contact/" className="text-link">Send a development brief ↗</Link></article></div></div></section>;}

export function PackingSupport({title}:{title?:string}={}){return <section className="section packing-support"><div className="wrap split"><div><p className="section-label">PACKING & SHIPPING</p><h2>{title||<>Export Packing & Delivery Support</>}</h2><p>Request a quotation covering containers, closures, protective packing and shipping. Provide the delivery destination and receiving requirements so we can review carton quantities, glass protection and any pallet needs.</p><Link className="button" href="/contact/">Request a packing & delivery quote ↗</Link></div><div className="packing-checklist"><h3>Packing Specifications</h3><ul><li><strong>Unit and carton counts</strong><span>State whether containers and closures should be packed together or separately.</span></li><li><strong>Glass protection</strong><span>Review dividers, inner protection and any pallet requirements for the selected jars.</span></li><li><strong>Identification</strong><span>Agree model references, carton marks and document details for receiving.</span></li><li><strong>Repeat orders</strong><span>Keep approved samples, artwork versions and cap specifications for reordering.</span></li></ul></div></div></section>;}
