import {CaseStudySection} from './components/CaseStudyCards';
import Link from 'next/link';
import {ProofStrip,HoneyApplications,DocumentProof,OrderJourney,FactoryEvidence,PackingSupport} from './components/TrustSections';
import {metadata as meta} from './seo';
import {categories,products,guides} from './data';
import {Photo,CTA,ProductGrid,FAQ} from './components/Common';
export const metadata=meta('Honey Packaging Supplier | Glass & Plastic | Gracepack','Source plastic honey bottles, glass honey jars and matching closures from Gracepack. Explore packaging formats, verified catalog sizes and custom options.');
export default function Home(){return <>
<section className="hero"><div className="wrap hero-grid"><div className="hero-copy"><h1>Gracepack: Your<br/>Honey Packaging<br/><em>Supplier in China</em></h1><p>Plastic Bottles, Glass Jars & Custom Packaging</p><p className="hero-description">Source honey containers for honey brands, packers, distributors and gift-pack projects. Gracepack supplies plastic bottles, glass jars and matching closures, with samples and customization reviewed for your order.</p><div className="actions"><Link className="button" href="/products/">Explore honey packaging ↗</Link><Link className="button outline" href="/contact/?request=sample">Request samples</Link></div><div className="hero-notes"><span>Plastic & glass</span><span>Matching closures</span><span>Custom options</span></div></div><div className="hero-visual"><Photo name="mini-glass-scene" alt="Small glass honey jars with gold lids on a wooden display" priority/><div className="hero-caption"><span>For tasting sets and branded honey lines</span><Link href="/mini-honey-jars/">Explore mini jars ↗</Link></div></div></div></section>
<ProofStrip/>
<section className="section"><div className="wrap"><div className="section-heading"><div><p className="section-label">BOTTLES, JARS & CLOSURES</p><h2>Honey Packaging Categories</h2></div><p>Choose by material, shape or dispensing style. Compare sizes, matching closures and product specifications within each range.</p></div><div className="category-grid">{categories.map(c=><Link className="category-card" href={`/${c.slug}/`} key={c.id}><Photo name={c.image} alt={c.title}/><div><h3>{c.title}</h3><span aria-hidden="true">↗</span></div></Link>)}</div></div></section>
<section className="section soft"><div className="wrap"><div className="section-heading"><div><p className="section-label">FEATURED PRODUCTS</p><h2>Wholesale Honey Bottles & Jars</h2></div><Link className="text-link" href="/products/">View the product range ↗</Link></div><ProductGrid items={products.filter(p=>['pet-honey-bear-bottle-320ml','ribbed-honey-squeeze-bottle-180ml','mini-glass-honey-jar-25ml'].includes(p.slug))}/></div></section>
<HoneyApplications title="Honey Packaging Applications"/>
<section className="section"><div className="wrap split story"><Photo name="squeeze-g07-use" alt="A ribbed honey squeeze bottle being dispensed through its flip-top cap"/><div><p className="section-label">CUSTOMIZATION SERVICES</p><h2>Custom Honey Packaging by Gracepack</h2><p>Select an existing container, customize its label and cap color, or discuss a new plastic bottle design. We review the container, closure and artwork together before sample approval.</p><ol className="steps"><li><strong>Choose the format</strong><span>Match material, volume and shape to your target honey fill.</span></li><li><strong>Specify closures & decoration</strong><span>Review the cap, label panel, color and outer packing.</span></li><li><strong>Approve the sample</strong><span>Check the assembled pack with your honey and filling process.</span></li></ol><Link className="text-link" href="/custom-honey-packaging/">Explore custom packaging ↗</Link></div></div></section>
<CaseStudySection/>
<section className="section soft home-about"><div className="wrap home-about-grid"><figure><img src="/assets/honey/gracepack-factory-entrance.webp" alt="Gracepack plastic packaging factory entrance in Cixi, Ningbo, China" width="720" height="487" loading="lazy"/><figcaption>Gracepack plastic packaging factory · Cixi, Ningbo, China</figcaption></figure><div className="home-about-copy"><p className="section-label">ABOUT GRACEPACK</p><h2>Honey Packaging Support from Gracepack in China</h2><p className="home-about-lead">Gracepack is based in Cixi, Ningbo and has worked in food packaging since 1999. We help honey brands, packers and packaging distributors select and develop honey containers for product lines, gift packs and bulk orders.</p><div className="home-about-points"><article><h3>Plastic bottles & caps</h3><p>PET honey bottles and matching plastic closures are manufactured through Cixi Yangen Plastic Industry Co., Ltd.</p></article><article><h3>Glass jars & metal lids</h3><p>Choose sourced glass jar formats with coordinated lids, samples, specifications and protective packing.</p></article><article><h3>Project support</h3><p>Review fill weight, dispensing, label area, customization and export packing with one Gracepack team.</p></article></div><Link className="button" href="/about/">About Gracepack ↗</Link></div></div></section>
<DocumentProof title="Gracepack Certifications & Test Reports"/>

<FactoryEvidence title="Gracepack Manufacturing & Product Development"/><OrderJourney title="How to Order from Gracepack"/><PackingSupport title="Export Packing & Delivery Support"/>
<section className="section"><div className="wrap"><div className="section-heading"><div><p className="section-label">PACKAGING KNOWLEDGE</p><h2>Honey Packaging Guides</h2></div><Link className="text-link" href="/resources/blog/">All packaging guides ↗</Link></div><div className="guide-grid">{guides.slice(0,3).map((g,i)=><Link className="guide-card" href={`/resources/blog/${g.slug}/`} key={g.slug}><span className="guide-number">0{i+1}</span><h3>{g.title}</h3><p>{g.description}</p><span className="text-link">Read the guide ↗</span></Link>)}</div></div></section>
<section className="section soft"><div className="wrap split"><div><h2>Honey Packaging FAQs</h2><Link className="text-link" href="/faq/">More answers ↗</Link></div><FAQ items={[["Do you sell honey or empty packaging?","We supply bottles, jars and packaging components. Honey shown in product photos is for presentation and is not included."],["Can I order both plastic and glass?","Yes. We offer plastic honey bottles and glass honey jars. Tell us your preferred formats so we can prepare the relevant options and quote."],["What are your minimum order quantities?","MOQ depends on the model, closure, color and customization. Share your target quantity and destination; we will confirm the order requirements for the selected pack."],["Can I request samples?","Yes. Send the product model and intended use. We will confirm sample availability, sample charges if applicable and shipping arrangements."]]}/></div></section><CTA title="Request a Honey Packaging Quote"/>
</>;}
