from pathlib import Path
import json,re,csv
root=Path(__file__).resolve().parents[1];ev=root/'content-evidence';src=json.loads((ev/'asset-review/master/products.json').read_text());dest=root/'content/honey-products.json'
if not (ev/'products-before-expansion.json').exists():(ev/'products-before-expansion.json').write_text(dest.read_text())
products=json.loads((ev/'products-before-expansion.json').read_text());assigned={};jobs=[]
def variant(i):
 x=src[i];t=x['parameters'];water=re.search(r'Water Capacity\s*:?\s*(\d+(?:\.\d+)?)\s*ML',t,re.I);honey=re.search(r'Honey Capacity\s*:?\s*(\d+(?:\.\d+)?)\s*G',t,re.I);cap=re.search(r',\s*([^\n]+?)\(cap\)',t,re.I)
 key='catalog-'+re.sub('[^a-z0-9]+','-',x['model'].lower()).strip('-')+'-'+str(i)
 if x['image']:jobs.append({'name':key,'source':x['image']})
 else:key='a54-concept'
 neck=x['neck'].strip();neck=neck if re.fullmatch(r'\d{2,3}-\d{3}',neck) else 'Confirm with selected sample'
 return {'model':re.sub(r'[\u4e00-\u9fff]+','',x['model']).strip()+(' (cap variant)' if i in [6,128] else ''),'volume':(water.group(1)+' ml') if water else 'Confirm with sample','honeyWeight':(honey.group(1)+' g') if honey else 'Confirm by filling trial','neck':neck,'closure':(cap.group(1).strip()+' cap') if cap else 'Confirm with sample','image':key,'imageKind':'AI concept; shape and closure are illustrative, not an approved A54 drawing' if i==72 else 'Original catalog reference image; approve the physical sample'}
def setvariants(p,ids):
 vs=[variant(i) for i in ids];p['variants']=vs;p['closure']=' / '.join(dict.fromkeys(v['closure'] for v in vs));p['imageKind']='Product photograph or catalog image; supplied empty';p['specNotes']='Catalog capacities are reference values. Each model is quoted and sampled separately; request its drawing and assembled closure before approval.'
 for i in ids:assigned[i]=p['slug']
oldids=[[64],[9],[59],[3],[77],[16],[46],[94,95,96],[91,92,93]]
for p,ids in zip(products,oldids):setvariants(p,ids)
groups=[
('cylindrical-honey-nozzle-bottles','Cylindrical Honey Nozzle Bottles',[0,51],['plastic','squeeze'],'Tall, straight-sided PET formats with dispensing closures. Compare A71 and A72 for label height and serving space; the smaller water volume does not imply the same honey fill weight.','The cylindrical body suits a wraparound label. Confirm how the artwork meets at the back and how much clear space is needed below the cap.'),
('ribbed-pet-honey-bottles','Ribbed PET Honey Bottle Series',[1,8,12,13,23,43,57,58,60,88],['plastic','squeeze'],'Ribbed honey bottles spanning compact sample packs to larger retail formats. Compare individual water capacities and neck finishes in the model table.','The ribs change the gripping surface and available label area. Compare a physical sample with the labeling equipment and review the intended dispensing closure.'),
('large-inverted-honey-bottle-720ml','720 ml Inverted Honey Bottle',[2],['plastic','squeeze'],'A larger PET bottle designed to stand cap-down, with a catalog reference honey fill of 1,000 g. The 38-400 neck is distinct from the smaller inverted models.','Check stability when nearly full and nearly empty. Confirm the assembled closure and evaluate flow with your own honey before specifying a valve.'),
('compact-inverted-honey-bottles','Compact Inverted Honey Bottles',[6,21,32,36,39,40,56,100,101,127],['plastic','squeeze'],'Cap-down PET formats in several body profiles and sizes. Each model has its own dimensions and closure arrangement; similar-looking caps are not interchangeable.','Compare shelf height, grip and the flat area available for artwork. For the G-36 cap variant, confirm the required tamper-evident arrangement separately.'),
('inverted-honey-bottle-360ml-g35','360 ml Inverted Honey Bottle — G-35',[5,128],['plastic','squeeze'],'Two catalog closure variants of the G-35 360 ml PET bottle. Choose the required cap arrangement and request the exact assembled sample.','The later catalog row identifies a cap without a tamper strip. List any seal or tamper-evident requirement in the inquiry rather than assuming it from the bottle profile.'),
('oval-inverted-honey-bottle-g12','360 ml Oval Inverted Honey Bottle — G-12',[30],['plastic','squeeze'],'An oval cap-down PET honey bottle with a 28-400 finish and 500 g reference fill. Its body profile offers a different grip from the ribbed upright series.','Evaluate label placement on both sides and confirm dispensing, resealing and standing stability with the selected cap.'),
('honey-jars-with-handles','PET Honey Jars with Carry Handles',[4,10,14,22,29,41,52],['plastic'],'Handled PET jars for larger honey packs, with model-specific mouth sizes and catalog water capacities from 500 to 2,200 ml.','The carry handle is part of the closure assembly. Check lifting, cap application, intended filled weight and carton clearance on the agreed sample.'),
('square-pet-honey-jars','Square PET Honey Jar Series',[11,87],['plastic'],'FD-85 and FD-100 use a compact jar profile with a 61-400 finish. Compare the 360 ml and 440 ml catalog formats for spoonable honey.','Check the usable flat panel and how the label wraps around the corners. Approve the actual fill level separately for each capacity.'),
('small-wide-mouth-honey-jars','Small Wide-Mouth PET Honey Jars',[18,49,82,86,108,115,121],['plastic'],'Compact screw-cap jars for smaller retail honey packs. This selection includes PP and PE closure materials, listed separately for each model.','Compare the mouth opening for filling and spoon access. Specify the liner or seal needed for the exact container and closure.'),
('pet-honey-bear-bottle-options','PET Honey Bear Bottle Options',[15,35,42,44,63],['plastic','bear'],'Additional bear-shaped PET models, including a 60 ml mini format and larger retail bottles. See the model table for the actual capacities and finishes.','Bear profiles differ in face details, grip and label panel. Evaluate artwork on the selected bear rather than treating the designs as interchangeable.'),
('pointed-cap-honey-bottles','Pointed-Cap PET Honey Bottles',[17,69,73,74,75,78,119],['plastic','squeeze'],'PET honey bottles with pointed dispensing-cap references and a choice of round or shaped bodies. Model-specific closure details are confirmed during sampling.','Review the outlet size and cap operation against the intended serving quantity. Catalog pictures show the style; the quote specifies the final cap.'),
('tall-pet-honey-bottles','Tall PET Honey Bottles',[19,31,34,65,66,67,68,129],['plastic'],'Slender and cylindrical PET bottles for honey ranges that need a taller shelf presentation. Models use different cap materials and neck arrangements.','Confirm the label panel length, filling nozzle clearance and the way the pack is stabilized during filling and labeling.'),
('flat-pet-honey-bottles','Flat-Profile PET Honey Bottles',[20,33,37,61,62],['plastic'],'Flat-profile PET formats with broad front and back faces. Compare the individual volume and closure requirements for retail honey packaging.','Use the front panel for the primary label and check the back label against the curve of the body. The selected cap should be tested with the actual honey.'),
('ribbed-wide-mouth-pet-honey-jars','Ribbed Wide-Mouth PET Honey Jars',[26,38,106,107,109,111],['plastic'],'Larger-mouth PET honey jars with ribbed or panelled bodies. The range provides alternatives to a narrow-neck dispensing bottle.','Compare spoon access and label position. A matching cap, liner and seal must be specified for each jar even when the apparent mouth size is similar.'),
('honey-bear-bottle-175ml-g02','175 ml PET Honey Bear Bottle — G-02',[28],['plastic','bear'],'A compact PET bear bottle with a catalog reference honey fill of 227 g. The catalog specifies an aluminium closure option.','The aluminium closure route differs from the flip-top PP caps on other bear models. Confirm the selected closure with the supplier before ordering.'),
('mini-pet-honey-nozzle-bottles','Mini PET Honey Nozzle Bottles',[71,102],['plastic','squeeze'],'Small PET dispensing formats for compact honey packs: A30 at 125 ml and YGS-HZP3024 at 60 ml.','Small labels need enough space for legible artwork. Review the cap opening and the actual honey dose with an assembled sample.'),
('wide-mouth-pet-honey-jar-shapes','Wide-Mouth PET Honey Jar Shapes',[79,80,89],['plastic'],'Alternative PET jar profiles for spoonable honey, with AD-1, AD-2 and AD-9 catalog references.','Compare the shoulder shape and usable label surface. Review the intended cap and sealing arrangement against each model rather than choosing by diameter alone.'),
('screw-cap-pet-honey-jars','Screw-Cap PET Honey Jar Series',[83,84,85,113,120,122,123],['plastic'],'PET jars with PE cap references, spanning compact retail sizes to larger honey packs. The table keeps capacity and closure information attached to each model.','Confirm the thread specification where the catalog does not list a complete neck finish. Final seal, liner and cap details should be written into the order.'),
('aluminium-cap-pet-honey-jars','PET Honey Jars with Aluminium Caps',[114,116,117,118],['plastic'],'PET honey jars with aluminium cap options for a metal-finish shelf appearance. Review the 360 ml and 730 ml catalog formats separately.','Check cap finish, liner compatibility and the required sealing method on the final jar. A metallic cap is not a guarantee of a particular seal system.'),
('round-pet-honey-jars','Round PET Honey Jar Formats',[103,104,105,112],['plastic'],'PET jar formats for honey with PP closure references and capacities from 360 to 725 ml.','Compare shoulder clearance, cap height and the label seam. Request the complete neck drawing and confirm the closure included in the quote.'),
('mini-glass-honey-jar-shapes','Mini Glass Honey Jar Shapes',[97,98,99],['glass','mini'],'Three additional small glass jar shapes at 80 or 100 ml, with tin lid references. These models extend the mini gift and tasting range.','Approve the lid and jar as one assembly. Compare the finished pack against your gift-box insert and protective packing.'),
('honey-bottle-a54-360ml','360 ml PET Honey Bottle — A54',[72],['plastic'],'The A54 catalog records a 360 ml PET body, a PP cap and a 500 g reference honey fill. Request the current drawing and physical sample to confirm the exact bottle and closure design.','The main image is an AI-generated concept because the catalog contains no picture for this entry. Shape, cap style and color are illustrative and must not be treated as the approved product drawing.'),
('oval-honey-bottles-g20-g21','Oval PET Honey Bottles — G-20 & G-21',[125,126],['plastic','squeeze'],'G-20 and G-21 offer oval PET honey formats with distinct closure references and catalog water capacities of 350 and 360 ml.','Match the dispensing arrangement to how your honey will be served. Ask for the complete neck and closure specification before confirming compatibility.')]
for slug,title,ids,cats,description,notes in groups:
 p={'slug':slug,'title':title,'model':' / '.join(src[i]['model'].split('盖子')[0].strip() for i in ids),'material':'Glass' if 'glass' in cats else 'PET','image':'','categories':cats,'description':description,'volume':'','honeyWeight':'','neck':'See model specifications','gallery':[]}
 setvariants(p,ids);p['image']=p['variants'][0]['image'];p['imageKind']=p['variants'][0]['imageKind'];p['specNotes']=notes
 p['volume']=' / '.join(dict.fromkeys(v['volume'] for v in p['variants']));p['honeyWeight']=' / '.join(dict.fromkeys(v['honeyWeight'] for v in p['variants']));products.append(p)
reasons={7:'表格250 ml与图片720 ml冲突',24:'表格420 ml与图片360 ml冲突',25:'口径38 mm与neck字段28-400冲突',27:'表格265 ml与图片210 ml冲突',45:'PET声明但瓶重441.5 g异常，需核实材质',47:'装饰双层罐，蜂蜜适用及结构需确认',48:'表格340 ml与图片420 ml冲突；PS复合结构需核实',50:'表格230 ml与图片200 ml冲突',53:'卡通装饰通用罐，包装用途待核实',54:'同型装饰变体，非独立蜂蜜产品',55:'容量768 ml与图片750 ml冲突',69:'表格720 ml与图片720 ml一致但母系列A28存在材质/容量冲突，待系列核实',70:'A28重复型号，另一行PP420 ml，本行PET360 ml，暂不自动选择',76:'口径36 mm与neck字段38-400冲突',81:'未列明材质',90:'另一本地产品图70 ml与总表100 ml冲突',110:'540 ml对应参考蜜重75 g异常',124:'RPET/RPP需再生比例及食品接触适用证据',130:'蜂巢盒非本次瓶罐产品范围，ABS盖应用待核实',131:'蜂巢盒非本次瓶罐产品范围，尺寸标注冲突',132:'ABS/PS蜂巢盒不属于本次瓶罐范围',133:'PP桶非本次瓶罐产品范围',134:'A28重复型号材质/容量冲突'}
rows=[]
for i,x in enumerate(src):rows.append({'sourceRow':i,'model':x['model'],'decision':'已映射' if i in assigned else '待核实/范围外','page':'/products/'+assigned[i]+'/' if i in assigned else '', 'reason':'型号和原始目录图/规格对应；缺失字段按待确认展示' if i in assigned else reasons.get(i,'未归入已核实系列，保留复核'),'sourceImage':x['image']})
for p in products:
 if p['material']=='PET' and 'jar' in p['title'].lower() and 'plastic-jars' not in p['categories']:p['categories'].append('plastic-jars')
dest.write_text(json.dumps(products,ensure_ascii=False,indent=2)+'\n');(ev/'catalog-expansion-assets.json').write_text(json.dumps(jobs,ensure_ascii=False,indent=2));(ev/'catalog-expansion-audit.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2))
with (ev/'catalog-expansion-audit.csv').open('w',encoding='utf-8-sig',newline='') as f:w=csv.DictWriter(f,fieldnames=rows[0]);w.writeheader();w.writerows(rows)
print('Pages',len(products),'source rows mapped',len(assigned),'held',len(src)-len(assigned),'assets',len(jobs))
