import ProductGallery from '../../components/ProductGallery';
import Inquiry from '../../components/Inquiry';
import {ProductSpecifications,ProductOrderDetails,productCopy} from '../../components/ProductSpecifications';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {products,categories,siteUrl,imageUrl} from '../../data';
import {metadata as meta,JsonLd} from '../../seo';
import {Breadcrumbs,ProductGrid,FAQ} from '../../components/Common';
export const dynamicParams=false;
export function generateStaticParams(){return products.map(p=>({slug:p.slug}));}
export function generateMetadata({params}:{params:{slug:string}}){const p=products.find(p=>p.slug===params.slug);return p?meta(p.title,`${p.description} Request samples and a bulk quote.`,`/products/${p.slug}/`,p.image):{};}
export default function ProductPage({params}:{params:{slug:string}}){
 const p=products.find(p=>p.slug===params.slug);if(!p)notFound();
 const single=p.variants.length===1,copy=productCopy[p.slug],first=p.variants[0],isClosure=p.categories.includes('closures');
 const others=products.filter(x=>x.slug!==p.slug&&(isClosure?x.categories.includes('closures'):x.material===p.material)).sort((a,b)=>b.categories.filter(c=>p.categories.includes(c)).length-a.categories.filter(c=>p.categories.includes(c)).length).slice(0,3);
 const capacities=p.variants.map(v=>parseFloat(v.volume)).filter(Number.isFinite);
 const volumeLabel=single?first.volume:capacities.length?`${Math.min(...capacities)}${Math.min(...capacities)!==Math.max(...capacities)?'–'+Math.max(...capacities):''} ml`:'';
 const honeyLabel=single&&!isClosure&&!/confirm/i.test(first.honeyWeight)?`Approx. ${first.honeyWeight} honey`:'';
 const quotePrompt=isClosure?'Include the closure name, compatible bottle or jar reference, quantity, color, outlet, liner or valve requirements and destination. We will confirm the proposed assembly and packing before quoting.':`Include the product name and selected capacity, your target honey fill, order quantity, decoration requirements and destination. We will confirm the proposed assembly and packing before quoting.`;
 const properties=isClosure?[{'@type':'PropertyValue',name:'Compatible finish',value:p.volume},{'@type':'PropertyValue',name:'Outlet / seal',value:p.honeyWeight}]:[{'@type':'PropertyValue',name:'Water capacity',value:p.volume},{'@type':'PropertyValue',name:'Reference honey fill',value:p.honeyWeight}];
 return <><div className="wrap"><Breadcrumbs items={[{name:'Products',url:'/products/'},{name:p.title,url:`/products/${p.slug}/`}]}/><div className="product-detail product-intro"><div className="product-intro-visual"><ProductGallery slug={p.slug} title={p.title}/></div><div className="product-intro-copy"><p className="meta">{isClosure?'Bulk closures for honey packaging':'Bulk honey packaging'}</p><h1>{p.title}</h1><p className="description">{p.description}</p><ul className="product-highlights" aria-label="Product highlights"><li>{p.material}</li>{volumeLabel&&<li>{volumeLabel}</li>}{honeyLabel&&<li>{honeyLabel}</li>}{!single&&<li>{p.variants.length} options</li>}</ul><a className="text-link full-spec-link" href="#specifications">{isClosure?'View compatibility details':single?'View full specifications':'Compare sizes & specifications'} ↓</a><Inquiry product={p.title} source="Product detail" compact lazy/></div></div></div><nav className="product-section-nav wrap" aria-label="Product details"><a href="#specifications">{isClosure?'Compatibility':'Specifications'}</a><a href="#application">{isClosure?'Application & fit':'Application & filling'}</a><a href="#ordering">Customization & orders</a><a href="#product-quality">Quality & reports</a></nav><ProductSpecifications product={p}/><ProductOrderDetails product={p}/><section className="section"><div className="wrap split"><div><h2>Product Questions & Ordering</h2><p>Answers about {p.title}, samples and quotation requirements.</p></div><FAQ items={[[copy.question,copy.answer],['What should I send for a quotation?',quotePrompt]]}/></div></section><section className="section soft"><div className="wrap"><h2>Related Honey Packaging</h2><ProductGrid items={others}/><div className="category-links">{categories.filter(c=>p.categories.includes(c.id)).map(c=><Link key={c.id} href={`/${c.slug}/`}>{c.title} ↗</Link>)}</div></div></section><JsonLd data={{'@context':'https://schema.org','@type':'Product',name:p.title,description:p.description,material:p.material,image:['full','closure','body','application'].map(view=>siteUrl+`/assets/honey-gallery/${p.slug}/${view}.webp`),url:siteUrl+`/products/${p.slug}/`,brand:{'@type':'Brand',name:'Gracepack'},additionalProperty:properties}}/></>;
}
